export enum FileEvents {
  Open = "file:open",
  ReadRequest = "file:read-request",
  Read = "file:read",
  WriteRequest = "file:write-request",
  Written = "file:written",
  Save = "file:save",
  Saved = "file:saved",
  Close = "file:close",
  RenameRequest = "file:rename-request",
  Renamed = "file:renamed",
  DeleteRequest = "file:delete-request",
  Deleted = "file:deleted",
  CopyRequest = "file:copy-request",
  Copied = "file:copied",
  MoveRequest = "file:move-request",
  Moved = "file:moved",
  CreateRequest = "file:create-request",
  Created = "file:created",
  ExistsRequest = "file:exists-request",
  Exists = "file:exists",
  UploadRequest = "file:upload-request",
  UploadProgress = "file:upload-progress",
  Uploaded = "file:uploaded",
  DownloadRequest = "file:download-request",
  DownloadProgress = "file:download-progress",
  Downloaded = "file:downloaded",
  Error = "file:error",
  StatRequest = "file:stat-request",
  Stat = "file:stat",
}

export enum FsEvents {
  ListRequest = "fs:list-request",
  Listed = "fs:listed",
  Change = "fs:change",
  Connected = "fs:connected",
  Disconnected = "fs:disconnected",
  WatchError = "fs:watch-error",
  StorageWarning = "fs:storage-warning",
}
