export enum GitEvents {
  Status = "git:status",
  Commit = "git:commit",
  Committed = "git:committed",
  Push = "git:push",
  Pushed = "git:pushed",
  Pull = "git:pull",
  Pulled = "git:pulled",
  BranchChange = "git:branch-change",
  Conflict = "git:conflict",
  ConflictResolved = "git:conflict-resolved",
  DiffOpen = "git:diff-open",
  Stage = "git:stage",
  Unstage = "git:unstage",
  StageCurrent = "git:stage-current",
  DiffCurrent = "git:diff-current",
  BlameCurrent = "git:blame-current",
}
