export enum VsixEvents {
  Install = "vsix:install",
  Installed = "vsix:installed",
  Uninstall = "vsix:uninstall",
  Uninstalled = "vsix:uninstalled",
  Activate = "vsix:activate",
  Deactivate = "vsix:deactivate",
  Error = "vsix:error",
  FetchStart = "vsix:fetch:start",
  FetchComplete = "vsix:fetch:complete",
  InstallStart = "vsix:install:start",
  InstallComplete = "vsix:install:complete",
  CommandRegistered = "vsix:command:registered",
  KeybindingRegistered = "vsix:keybinding:registered",
  ThemesLoaded = "vsix:themes:loaded",
  IconsLoaded = "vsix:icons:loaded",
  CacheCleared = "vsix:cache:cleared",
  Ready = "vsix:ready",
}
