export enum WebviewEvents {
  Create = "webview:create",
  Show = "webview:show",
  Hide = "webview:hide",
  Dispose = "webview:dispose",
  Message = "webview:message",
  Post = "webview:post",
  Focus = "webview:focus",
  StateSave = "webview:state-save",
  StateRestore = "webview:state-restore",
  Error = "webview:error",
  BeforeMount = "webview:before-mount",
  AfterMount = "webview:after-mount",
  LoaderStart = "webview:loader-start",
  LoaderDone = "webview:loader-done",
  ActionStart = "webview:action-start",
  ActionDone = "webview:action-done",
  ActionError = "webview:action-error",
  Registered = "webview:registered",
  LazyCreate = "webview:lazy-create",
  FsRead = "webview:fs-read",
  FsWrite = "webview:fs-write",
  FsList = "webview:fs-list",
  SettingRead = "webview:setting-read",
  SettingWrite = "webview:setting-write",
}
